models/Project.php
<?php

namespace app\models;

use yii\data\ArrayDataProvider;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * Class Project
 *
 * @property int $id
 * @property int $user_id
 * @property string $name
 *
 * @property Task[] $tasks
 *
 * @package app\models
 */
class Project extends ActiveRecord
{

    /**
     * @return string
     */
    public static function tableName(): string
    {
        return '{{%project}}';
    }

    /**
     * @return array|array[]
     */
    public function rules(): array
    {
        return [
            [['user_id'], 'safe'],
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getTasks(): ActiveQuery
    {
        return $this->hasMany(Task::class, ['project_id' => 'id'])->orderBy(['priority' => SORT_ASC]);
    }

    /**
     * @return ArrayDataProvider
     */
    public function getAll(): ArrayDataProvider
    {
        return new ArrayDataProvider([
            'allModels' => $this->tasks,
        ]);
    }
}

controllers/ProjectController.php
<?php

namespace app\controllers;

use Yii;
use Throwable;
use yii\web\Response;
use app\models\Project;
use yii\web\Controller;
use yii\widgets\ActiveForm;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;

/**
 * Class ProjectController
 *
 * @package app\controllers
 */
class ProjectController extends Controller
{

    /**
     * @return array|array[]
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ],
                'denyCallback' => static function () {
                    return Yii::$app->response->redirect(['/site/index']);
                },
            ]
        ];
    }

    /**
     * @return string
     *
     * @author Marina Senko
     */
    public function actionIndex(): string
    {
        $projects = Project::find()
            ->where(['user_id' => Yii::$app->user->id])
            ->all();

        return $this->render('index', [
            'projects' => $projects,
        ]);
    }

    /**
     * @return string|Response
     * @throws Throwable
     */
    public function actionCreate()
    {
        $model = new Project();
        $this->performAjaxValidation($model);

        if ($model->load(Yii::$app->request->post())) {
            $errorMessage = 'Error creating project';
            try {
                $model->user_id = Yii::$app->user->id;
                if (!$model->save()) {
                    Yii::$app->session->setFlash('error', $errorMessage);
                } else {
                    return $this->redirect(['index']);
                }
            } catch (Throwable $e) {
                Yii::$app->session->setFlash('error', $errorMessage);
            }
        }

        return $this->redirect(['index']);
    }

    /**
     * @param int $id
     * @return Response
     * @throws NotFoundHttpException
     * @throws Throwable
     */
    public function actionUpdate(int $id)
    {
        $model = $this->findModel($id);
        $this->performAjaxValidation($model);

        if ($model->load(Yii::$app->request->post())) {
            try {
                $errorMessage = 'Error updating project';
                if (!$model->save()) {
                    Yii::$app->session->setFlash('error', $errorMessage);
                }
            } catch (Throwable $e) {
                Yii::$app->session->setFlash('error', $errorMessage);
            }
            return $this->redirect(['index']);
        }

        return $this->redirect(['index']);
    }

    /**
     * @param int $id
     * @return Response
     */
    public function actionDelete(int $id): Response
    {
        try {
            $errorMessage = 'Error deleting project';
            if (!$this->findModel($id)->delete()) {
                Yii::$app->session->setFlash('error', $errorMessage);
            }
        } catch (Throwable $e) {
            Yii::$app->session->setFlash('error', $errorMessage);
        }
        return $this->redirect(['index']);
    }

    /**
     * @param int $id
     * @return array|\yii\db\ActiveRecord
     * @throws NotFoundHttpException
     */
    protected function findModel(int $id)
    {
        $model = Project::find()
            ->where(['user_id' => Yii::$app->user->id])
            ->andWhere(['id' => $id])
            ->one();

        if ($model !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * @param $model
     * @throws Throwable
     */
    private function performAjaxValidation($model): void
    {
        if (Yii::$app->request->isAjax && !Yii::$app->request->isPjax) {
            if ($model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                Yii::$app->response->data = ActiveForm::validate($model);
                Yii::$app->end();
            }
        }
    }
}

controllers/TaskController.php
<?php

namespace app\controllers;

use Yii;
use Throwable;
use app\models\Task;
use yii\web\Response;
use yii\web\Controller;
use yii\db\ActiveRecord;
use yii\widgets\ActiveForm;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;

/**
 * Class TaskController
 * @package app\controllers
 */
class TaskController extends Controller
{

    /**
     * @return array|array[]
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ],
                'denyCallback' => static function () {
                    return Yii::$app->response->redirect(['/site/index']);
                },
            ]
        ];
    }

    /**
     * @return string|Response
     * @throws Throwable
     */
    public function actionCreate()
    {
        $model = new Task();
        $this->performAjaxValidation($model);

        if ($model->load(Yii::$app->request->post())) {
            $errorMessage = 'Error creating task';
            try {
                if (!$model->save()) {
                    Yii::$app->session->setFlash('error', $errorMessage);
                }
            } catch (Throwable $e) {
                Yii::$app->session->setFlash('error', $errorMessage);
            }
        }

        return $this->redirect(['/project/index']);
    }

    /**
     * @param $id
     * @return string|Response
     * @throws NotFoundHttpException
     * @throws Throwable
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $this->performAjaxValidation($model);

        if ($model->load(Yii::$app->request->post())) {
            try {
                $errorMessage = 'Error updating task';
                if (!$model->save()) {
                    Yii::$app->session->setFlash('error', $errorMessage);
                }
            } catch (Throwable $e) {
                Yii::$app->session->setFlash('error', $errorMessage);
            }
        }

        return $this->redirect(['/project/index']);
    }

    /**
     * @param $id
     * @return Response
     */
    public function actionDelete($id): Response
    {
        try {
            $errorMessage = 'Error deleting task';
            if (!$this->findModel($id)->delete()) {
                Yii::$app->session->setFlash('error', $errorMessage);
            }
        } catch (Throwable $e) {
            Yii::$app->session->setFlash('error', $errorMessage);
        }
        return $this->redirect(['/project/index']);
    }

    /**
     * @param int $id
     * @return Response
     * @throws NotFoundHttpException
     */
    public function actionChangeStatus(int $id)
    {
        /**
         * @var Task $model
         */
        $model = $this->findModel($id);

        try {
            $errorMessage = 'Error change task status';
            if (!$model->changeStatus()) {
                Yii::$app->session->setFlash('error', $errorMessage);
            }
        } catch (Throwable $e) {
            Yii::$app->session->setFlash('error', $errorMessage);
        }

        return $this->redirect(['/project/index']);
    }

    /**
     * @param int $id
     * @return Response
     * @throws NotFoundHttpException
     */
    public function actionUp(int $id)
    {
        /**
         * @var Task $model
         */
        $model = $this->findModel($id);

        try {
            $errorMessage = 'Error change task priority';
            if (!$model->upPriority()) {
                Yii::$app->session->setFlash('error', $errorMessage);
            }
        } catch (Throwable $e) {
            Yii::$app->session->setFlash('error', $errorMessage);
        }

        return $this->redirect(['/project/index']);
    }

    /**
     * @param int $id
     * @return Response
     * @throws NotFoundHttpException
     */
    public function actionDown(int $id)
    {
        /**
         * @var Task $model
         */
        $model = $this->findModel($id);

        try {
            $errorMessage = 'Error change task priority';
            if (!$model->downPriority()) {
                Yii::$app->session->setFlash('error', $errorMessage);
            }
        } catch (Throwable $e) {
            Yii::$app->session->setFlash('error', $errorMessage);
        }

        return $this->redirect(['/project/index']);
    }

    /**
     * @param $id
     * @return array|ActiveRecord
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        $model = Task::find()
            ->innerJoin('project', 'project.id = task.project_id')
            ->andWhere(['project.user_id' => Yii::$app->user->id])
            ->andWhere(['task.id' => $id])
            ->one();

        if ($model !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * @param ActiveRecord $model
     * @throws Throwable
     */
    private function performAjaxValidation(ActiveRecord $model): void
    {
        if (Yii::$app->request->isAjax && !Yii::$app->request->isPjax) {
            if ($model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                Yii::$app->response->data = ActiveForm::validate($model);
                Yii::$app->end();
            }
        }
    }
}

views/project/_create_task.php
<?php

use yii\web\View;
use yii\helpers\Url;
use app\models\Task;
use app\models\Project;
use yii\helpers\Html;
use kartik\form\ActiveForm;

/**
 * @var View $this
 * @var Project $project
 */

$model = new Task();


$form = ActiveForm::begin([
    'action' => Url::to(['/task/create']),
    'options' => ['style' => 'margin: 10px 0']
]);

echo $form->field($model, 'project_id')->hiddenInput(['value' => $project->id])->label(false);
echo $form->field($model, 'name', [
                'addon' => [
                    'append' => [
                        'content' => Html::submitButton('Add task', ['class' => 'btn btn-success', 'name' => 'project-button']),
                        'asButton' => true
                    ],
                    'prepend' => [
                        'content' => '<i class="fas fa-plus"></i>'
                    ],
                ],

            ])->label(false);

ActiveForm::end();

views/project/_item.php
<?php

use yii\web\View;
use yii\helpers\Url;
use yii\helpers\Html;
use app\models\Task;
use app\models\Project;
use kartik\grid\GridView;

/**
 * @var View $this
 * @var Project $project
 */

$model = new Task();

$gridColumns = [
    ['class' => 'kartik\grid\SerialColumn'],
    [
        'label' => '',
        'contentOptions' => [
            'width' => '5%'
        ],
        'attribute' => 'status',
        'format' => 'raw',
        'value' => static function (Task $model) {
            return Html::checkbox(
                '',
                $model->status === Task::STATUS_COMPLETED,
                [
                    'class' => 'task-done',
                    'data-id' => $model->id,
                    'id' => 'task-done-' . $model->id
                ]
            );
        }
    ],
    [
        'attribute' => 'name',
        'vAlign' => 'middle',
    ],
    [
        'label' => '',
        'contentOptions' => [
            'width' => '15%'
        ],
        'attribute' => 'status',
        'format' => 'raw',
        'value' => function (Task $model) use ($project) {
            echo $this->render('_update_task', ['model' => $model, 'project' => $project]);
            return Html::a('<i class="fas fa-chevron-up"></i><span> </span>', ['/task/up', 'id' => $model->id]) .
                Html::a('<i class="fas fa-chevron-down"></i><span> </span>', ['/task/down', 'id' => $model->id]) .
                Html::a('<i class="fas fa-edit"></i><span> </span>', '#',
                    ['class' => 'edit-task', 'data-id' => $model->id]) .
                Html::a('<i class="fas fa-trash"></i>', ['/task/delete', 'id' => $model->id]);
        }
    ],
];

?>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <?= GridView::widget([
                'dataProvider' => $project->getAll(),
                'rowOptions' => static function (Task $model) {
                    if ($model->status !== Task::STATUS_COMPLETED
                        && !empty($model->deadline)
                        && $model->deadline < time()
                    ) {
                        return ['class' => 'danger'];
                    } elseif ($model->status === Task::STATUS_COMPLETED) {
                        return ['class' => 'success'];
                    }
                },
                'columns' => $gridColumns,
                'pjax' => true,
                'containerOptions' => ['style' => 'overflow: auto'],
                'bordered' => true,
                'striped' => false,
                'condensed' => false,
                'responsive' => true,
                'hover' => true,
                'floatHeader' => true,
                'itemLabelSingle' => 'task',
                'itemLabelPlural' => 'tasks',
                'summary' => '',
                'panel' => [
                    'type' => GridView::TYPE_PRIMARY,
                    'heading' => '<i class="fa fa-calendar" aria-hidden="true"></i><span> ' . $project->name . ' </span><a href="' . Url::to([
                            '/project/delete',
                            'id' => $project->id
                        ]) . '" class="pull-right"><i class="fas fa-trash"></i></a>'
                        . '<a href="#" class="pull-right edit-project" id="edit-project-' . $project->id . '" data-id="' . $project->id . '"><i class="fas fa-edit"></i></a>'
                ],
                'toolbar' => [
                    [
                        'content' => $this->render('_create_task', ['project' => $project]),
                        'options' => ['class' => 'btn-group mr-2']
                    ],
                ],
            ]) ?>
        </div>
    </div>

<?= $this->render('_update_project', ['project' => $project]) ?>

    <br>
    <br>

<?php $js = <<<JS
$(document).ready(function() {
  $('.edit-project').click(function() {
      let id = $(this).data('id');
      $('#modal-project-' + id).modal('show');  
  });
  $('.edit-task').click(function() {
      let id = $(this).data('id');
      $('#edit-task-' + id).modal('show');  
  });
   $('.task-done').change(function() {
    let id = $(this).data('id');
     $.ajax({
            url: '/task/change-status?id=' + id,
            type: 'post',
            dataType: 'json',
            data: $('form#news-form').serialize(),
        });
  });
});
JS;
$this->registerJs($js, View::POS_END);

views/project/_task_form.php
<?php

use yii\web\View;
use yii\helpers\Html;
use app\models\Task;
use app\models\Project;
use yii\bootstrap\ActiveForm;
use trntv\yii\datetime\DateTimeWidget;


/**
 * @var View $this
 * @var Project $project
 * @var Task $model
 * @var ActiveForm $form
 */


echo $form->field($model, 'name')->textInput(['maxlength' => 255]);
echo $form->field($model, 'project_id')->hiddenInput(['value' => $project->id])->label(false);
echo $form->field($model, 'deadline')->widget(DateTimeWidget::class,
    [
        'phpDatetimeFormat' => 'yyyy-MM-dd\'T\'HH:mm:ssZZZZZ',
        'clientOptions' => [
            'allowInputToggle' => false,
            'sideBySide' => true,
            'locale' => 'en-Us',
            'widgetPositioning' => [
                'horizontal' => 'auto',
                'vertical' => 'auto'
            ]
        ]

    ]);

echo Html::submitButton('Save', ['class' => 'btn btn-primary']);

views/project/_update_project.php
<?php

use yii\web\View;
use yii\helpers\Url;
use yii\helpers\Html;
use app\models\Project;
use yii\bootstrap\Modal;
use yii\bootstrap\ActiveForm;

/**
 * @var View $this
 * @var Project $project
 */


Modal::begin([
    'id' => 'modal-project-' . $project->id,
    'size' => 'modal-md',
    'header' => '<h2>Edit project</h2>',
]);

$form = ActiveForm::begin([
    'action' => Url::to(['/project/update', 'id' => $project->id])
]);

echo $form->field($project, 'name')->textInput(['maxlength' => 255]);
echo Html::submitButton('Save', ['class' => 'btn btn-primary']);

ActiveForm::end();
Modal::end();

views/project/_update_task.php
<?php

use yii\web\View;
use yii\helpers\Url;
use app\models\Task;
use app\models\Project;
use yii\bootstrap\Modal;
use yii\bootstrap\ActiveForm;


/**
 * @var View $this
 * @var Project $project
 * @var Task $model
 */


Modal::begin([
    'id' => 'edit-task-' . $model->id,
    'size' => 'modal-md',
    'header' => '<h2>Edit task</h2>',
]);
$form = ActiveForm::begin([
    'action' => Url::to(['/task/update', 'id' => $model->id]),
]);

echo $this->render('_task_form', ['model' => $model, 'form' => $form, 'project' => $project]);

ActiveForm::end();
Modal::end();

views/project/index.php
<?php

use yii\web\View;
use yii\helpers\Url;
use yii\helpers\Html;
use app\models\Project;
use kartik\form\ActiveForm;

/**
 * @var $this View
 * @var Project[] $projects
 */

$model = new Project();

?>

<div class="text-center">
    <h2>SIMPLE TODO LISTS</h2>
    <h4>FROM RUBY GARAGE</h4>
</div>

<div class="project-block">
    <?php foreach ($projects as $project): ?>
        <?= $this->render('_item', ['project' => $project]) ?>
    <?php endforeach ?>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <?php $form = ActiveForm::begin([
                'id' => 'project-form',
                'action' => Url::to(['/project/create']),
            ]); ?>

            <?= $form->field($model, 'name', [
                'addon' => [
                    'append' => [
                        'content' => Html::submitButton('<i class="fas fa-plus"></i> Add TODO list', ['class' => 'btn btn-primary', 'name' => 'project-button']),
                        'asButton' => true
                    ]
                ]
            ])->label(false) ?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>